package infra

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// Backend is examples/aws/backend/<env>.hcl, written by the bootstrap stack and
// consumed by every later init.
type Backend struct {
	// Path is the absolute path of the file it was read from.
	Path string
	// Bucket is named lerian-tfstate-<env>-<account_id> by bootstrap, which is what
	// makes it carry the account id and therefore checkable offline.
	Bucket string
	// Region is where the state lives.
	Region string
}

// ErrNoBackendFile is returned when backend/<env>.hcl is absent, which is the
// normal state of an environment that has not been bootstrapped yet.
var ErrNoBackendFile = errors.New("infra: backend file not found")

// ErrWrongAccount is returned by VerifyAccount when the live credentials resolve
// to an account other than the declared one. It is deliberately impossible to
// bypass: applying one environment into another environment's account is the
// failure this package exists to prevent.
var ErrWrongAccount = errors.New("infra: wrong AWS account")

// LoadBackend reads and parses backend/<env>.hcl. It does not verify the account;
// CheckBackend does that.
func LoadBackend(layout Layout, env string) (Backend, error) {
	path := layout.BackendFile(env)

	file, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Backend{}, fmt.Errorf("%w: %s\n"+
				"Every stack except bootstrap initialises its S3 backend from this file, and\n"+
				"it is generated by the bootstrap stack rather than committed, because it\n"+
				"carries the AWS account id.\n\n"+
				"  lerian-infra --env %s --target bootstrap --action apply\n\n"+
				"If the bucket already exists but the file does not — a fresh clone, or another\n"+
				"operator ran the bootstrap — write it by hand; see %s/README.md.",
				ErrNoBackendFile, layout.RepoRel(path), env, layout.RepoRel(layout.BackendDir()))
		}
		return Backend{}, fmt.Errorf("infra: cannot read %s: %w", layout.RepoRel(path), err)
	}
	defer func() { _ = file.Close() }()

	backend := Backend{Path: path}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		key, value, ok := parseHCLAssignment(scanner.Text())
		if !ok {
			continue
		}
		switch key {
		case "bucket":
			if backend.Bucket == "" {
				backend.Bucket = value
			}
		case "region":
			if backend.Region == "" {
				backend.Region = value
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return Backend{}, fmt.Errorf("infra: cannot read %s: %w", layout.RepoRel(path), err)
	}

	if backend.Bucket == "" {
		return Backend{}, fmt.Errorf("infra: %s has no 'bucket' line\nIt should look like:\n\n"+
			"  bucket         = \"lerian-tfstate-%s-<account_id>\"\n"+
			"  region         = \"us-east-2\"\n"+
			"  dynamodb_table = \"lerian-tfstate-lock-%s\"\n  encrypt        = true",
			layout.RepoRel(path), env, env)
	}
	return backend, nil
}

// parseHCLAssignment reads one `key = "value"` line of a backend file. Anything
// else — a comment, a blank line, a block — yields ok=false.
func parseHCLAssignment(line string) (key, value string, ok bool) {
	line = strings.TrimSpace(line)
	if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "//") {
		return "", "", false
	}
	separator := strings.Index(line, "=")
	if separator < 0 {
		return "", "", false
	}
	key = strings.TrimSpace(line[:separator])
	value = strings.TrimSpace(line[separator+1:])
	value = strings.Trim(value, `"`)
	if key == "" || value == "" {
		return "", "", false
	}
	return key, value, true
}

// BackendWarning is a disagreement that is suspicious but not proof of an error,
// so it is reported rather than fatal.
type BackendWarning string

// CheckBackend is the offline half of the account guard, and it is the half that
// catches the common mistake without spending a single AWS call.
//
// Guard 1: bootstrap names the bucket lerian-tfstate-<env>-<account_id>, so the
// backend file already states which account this environment lives in. When that
// disagrees with environments.conf, one of the two is stale — and without this
// check the run dies much later with a 403 that explains nothing.
//
// Guard 2: the region in the backend file must match the region in the config,
// because state for this environment physically lives in one of them.
func CheckBackend(layout Layout, config EnvConfig, backend Backend) ([]BackendWarning, error) {
	if !strings.HasSuffix(backend.Bucket, "-"+config.AccountID) {
		return nil, fmt.Errorf("infra: account mismatch between %s and %s\n"+
			"  [%s] account_id declares : %s\n"+
			"  the backend bucket says  : %s\n\n"+
			"The bucket is named lerian-tfstate-<env>-<account_id>, so these two disagree\n"+
			"about which account '%s' lives in. One of them is stale. Fix the config, or\n"+
			"re-run bootstrap for this environment to regenerate the backend file.",
			layout.RepoRel(layout.ConfigFile()), layout.RepoRel(backend.Path),
			config.Environment, config.AccountID, backend.Bucket, config.Environment)
	}

	if backend.Region != "" && backend.Region != config.Region {
		return nil, fmt.Errorf("infra: region mismatch between %s and %s\n"+
			"  [%s] region declares : %s\n"+
			"  the backend file says : %s\n\n"+
			"State for this environment lives in one of those two regions. Either the config\n"+
			"is wrong or the environment was bootstrapped somewhere else.",
			layout.RepoRel(layout.ConfigFile()), layout.RepoRel(backend.Path),
			config.Environment, config.Region, backend.Region)
	}

	var warnings []BackendWarning
	// Not fatal: the account suffix already matched, so this is a bucket that was
	// named by hand rather than by bootstrap. Worth saying, not worth stopping for.
	if !strings.Contains(backend.Bucket, "-"+config.Environment+"-") {
		warnings = append(warnings, BackendWarning(fmt.Sprintf(
			"backend bucket %q does not contain %q; bootstrap would have named it lerian-tfstate-%s-%s",
			backend.Bucket, "-"+config.Environment+"-", config.Environment, config.AccountID)))
	}
	return warnings, nil
}

// Caller is who the active credentials say they are.
type Caller struct {
	Account string
	ARN     string
}

// Identity resolves the AWS identity a profile currently has. It is an interface
// so the account guard can be tested without credentials, and so the resolution
// can later move from the AWS CLI to the SDK without touching the guard.
type Identity interface {
	// CallerIdentity returns who profile resolves to in region. An empty profile
	// means ambient credentials.
	CallerIdentity(ctx context.Context, profile, region string) (Caller, error)
}

// CLIIdentity resolves the identity by calling the AWS CLI, which is the same
// resolution the shell version verified and the same shared-config rules the
// Terraform AWS provider follows.
type CLIIdentity struct {
	// Binary is the aws executable. Empty means "aws" from PATH.
	Binary string
}

// CallerIdentity runs `aws sts get-caller-identity`.
func (c CLIIdentity) CallerIdentity(ctx context.Context, profile, region string) (Caller, error) {
	binary := c.Binary
	if binary == "" {
		binary = "aws"
	}

	command := exec.CommandContext(ctx, binary,
		"sts", "get-caller-identity", "--region", region,
		"--query", "[Account,Arn]", "--output", "text")
	command.Env = os.Environ()
	if profile != "" {
		command.Env = append(command.Env, "AWS_PROFILE="+profile)
	}

	output, err := command.CombinedOutput()
	if err != nil {
		return Caller{}, fmt.Errorf("aws sts get-caller-identity failed: %w\n%s",
			err, strings.TrimSpace(string(output)))
	}

	fields := strings.Fields(string(output))
	if len(fields) < 2 {
		return Caller{}, fmt.Errorf("aws sts get-caller-identity returned %q, expected an account and an ARN",
			strings.TrimSpace(string(output)))
	}
	return Caller{Account: fields[0], ARN: fields[1]}, nil
}

// VerifyAccount is the third guard and the one that matters: it refuses to
// continue when the live credentials resolve to an account other than the one
// environments.conf declares for this environment.
//
// There is no flag to skip it. If the account genuinely changed, environments.conf
// is edited — a reviewable, diffable act.
func VerifyAccount(ctx context.Context, identity Identity, config EnvConfig) (Caller, error) {
	caller, err := identity.CallerIdentity(ctx, config.Profile, config.Region)
	if err != nil {
		hint := "If this is an SSO profile the session has probably expired:\n  aws sso login --profile " + config.Profile
		if config.Profile == "" {
			hint = "No profile is configured for this environment, so ambient credentials were used:\n" +
				"check AWS_ACCESS_KEY_ID / AWS_SESSION_TOKEN, or the instance role."
		}
		return Caller{}, fmt.Errorf("infra: cannot verify the AWS identity for '%s': %w\n\nprofile: %s\n%s",
			config.Environment, err, profileLabel(config.Profile), hint)
	}

	if caller.Account != config.AccountID {
		return caller, fmt.Errorf("%w — refusing to touch '%s'\n"+
			"  environments.conf declares [%s] : %s\n"+
			"  active credentials resolve to    : %s\n"+
			"  identity                         : %s\n"+
			"  profile                          : %s\n\n"+
			"Nothing has been planned, applied or destroyed.\n\n"+
			"Either the profile for [%s] is wrong in environments.conf, or AWS_PROFILE /\n"+
			"AWS_ACCESS_KEY_ID in this shell is overriding it. There is no flag to skip this\n"+
			"check: applying one environment into another environment's account is the\n"+
			"failure this tool exists to prevent.",
			ErrWrongAccount, config.Environment,
			config.Environment, config.AccountID,
			caller.Account, caller.ARN, profileLabel(config.Profile),
			config.Environment)
	}
	return caller, nil
}

func profileLabel(profile string) string {
	if profile == "" {
		return "<ambient credentials>"
	}
	return profile
}
