package main

// usage is written by hand rather than generated by the flag package: the flags of
// this command need paragraphs, not one-line descriptions, because most of them
// select which AWS account gets touched.
const usage = `lerian-infra — deploy the AWS v2 stacks of lerian-terraform-foundation

USAGE
  lerian-infra init --env <dev|stg|prd> [flags]        write the configuration
  lerian-infra --env <dev|stg|prd> [--target <target>] [--action <action>] [options]

FIRST RUN
  A fresh checkout has no configuration: environments.conf and every
  envs/<env>.tfvars are gitignored, because they carry an AWS account id. The init
  subcommand writes them, asking for what it cannot discover:

    lerian-infra init --env dev

  It lists the AWS profiles it found with the account each one reaches, detects
  this machine's egress address for the cluster's API allow-list, and materialises
  one tfvars per root from the committed *.tfvars-example next to it. Nothing it
  does touches an AWS resource. Run 'lerian-infra init --help' for its flags —
  every question it asks has one, so CI never has to answer a prompt.

FLAGS
  --repo <path>           The lerian-terraform-foundation checkout to drive.
                          Rarely needed: this command is built from the checkout
                          it drives, so running it anywhere inside one is enough.
                          Resolution order:
                            1. --repo
                            2. $LERIAN_TF_REPO
                            3. walk up from the working directory until a
                               directory holding examples/aws/_modules and
                               examples/aws/backend is found.
                            4. the managed checkout, ~/lerian/lerian-terraform-foundation
                          The managed checkout is LAST on purpose: an operator
                          working inside a development checkout must keep driving
                          that one, not the managed tree that also happens to
                          exist. Only init may create it — a run that downloaded
                          a repository halfway through would be a surprise.

  --templates-dir <path>  Where the managed checkout lives, when not the default.

  --env <dev|stg|prd>     REQUIRED. Selects the AWS account from
                          examples/aws/environments.conf, the backend file
                          examples/aws/backend/<env>.hcl, and the variables file
                          envs/<env>.tfvars inside every stack.

  --target <target>       What to operate on. Default: infra-base.
                            bootstrap                state bucket + lock table
                            infra-base               vpc then eks
                            infra-base/vpc           just the VPC
                            infra-base/eks           just the cluster
                            shared-resources         the whole shared datastore tier
                            shared-resources/<svc>   one shared datastore
                            <product>                every service of one product
                            <product>/<service>      one service
                            all                      everything, in order
                          Several targets can be combined with commas:
                            --target infra-base,midaz
                          The parts are reordered into dependency order, so
                          "midaz,infra-base" and "infra-base,midaz" run the same
                          way and neither can put a datastore before its VPC.
                          Products and services are DISCOVERED from
                          examples/aws/products/*/*/main.tf. A new product works
                          the moment its directory exists. Run --list to see them.

  --action <action>       Default: plan.
                            plan          terraform plan only. Changes nothing.
                            apply         plan, show the summary, confirm, apply.
                            destroy       the same, for -destroy plans.
                            helm-values   read helm_values from every service of
                                          the target and merge them into one
                                          document on stdout.
                            output        terraform output for every unit.

  --auto-approve          Skip the single confirmation before apply/destroy.
                          Terraform still applies a saved plan file, so what runs
                          is exactly what was shown.

  --jobs <n>              Services inside one product run in parallel. Default 4.
                          Ordered stages (bootstrap, vpc, eks) are always
                          sequential regardless of this.

  --format <json|yaml>    Output shape for --action helm-values. Default json.

  --dry-run               Resolve and print the execution plan — units, order,
                          state keys, backend file, profile, expected account —
                          then exit. Makes NO AWS call at all.

  --list                  List discoverable targets and exit. Makes no AWS call,
                          reads no configuration.

  --version               Print the version and exit.
  --help                  This text.

THE ACCOUNT GUARD
  Three checks run before anything else, and two of them cost no AWS call:

    1. the state bucket in backend/<env>.hcl ends in -<account_id>, which catches
       a backend file left over from another account;
    2. the region in environments.conf matches the one in backend/<env>.hcl;
    3. aws sts get-caller-identity resolves to the declared account_id.

  There is deliberately no flag to bypass any of them, and --auto-approve does not
  skip them. If the account genuinely changed, edit environments.conf — a
  reviewable, diffable act — instead of typing an override at the end of a long
  day.

THE SHARED TIER IS OPT-IN PER ENGINE
  shared-resources holds five engines because five exist in AWS, not because any
  environment wants all five. An engine with no envs/<env>.tfvars is skipped and
  reported by name, so "apply the shared tier" is not refused because of a
  datastore nobody uses — MSK, whose floor is three brokers, being the usual one.

  For a PRODUCT this does not apply: every datastore under it is required by its
  chart, so a missing tfvars there stays an error.

  S3 is never shared, and that is why the tier has no s3 root. A bucket holds one
  application's objects under one policy, one lifecycle and one key, so the roots
  that own one — br-sfn, fetcher, plugin-bc-correios, reporter — carry no mode
  switch. Shared mode leaves them alone: they still create a real bucket, and they
  still need to be applied along with the product.

WHERE helm-values READS FROM
  A product in shared mode creates nothing: its roots resolve the tier that owns
  the datastores. For products whose chart mapping has been ported into this
  binary, helm-values reads the tier's state directly and never touches the
  product root, so there is no apply of a root that would build nothing. For every
  other product it reads the product root's own helm_values output, which requires
  that root to have been applied.

ORDER
  apply    bootstrap -> infra-base/vpc -> infra-base/eks
                     -> shared-resources/* -> products/*
  destroy  the exact reverse.

  bootstrap is never destroyed: the bucket and the lock table carry
  prevent_destroy = true. See examples/aws/bootstrap/README.md, "Teardown".

WHY -reconfigure IS ALWAYS PASSED
  .terraform/ caches the resolved backend, including the bucket of whichever
  environment was initialised last. Without -reconfigure, switching environments
  in the same checkout keeps the stale bucket and the run dies with a 403 at apply
  time — long after the plan looked fine. Every init here passes it.

ENVIRONMENT VARIABLES
  LERIAN_TF_REPO      The checkout to drive, when not running inside one.
  LERIAN_TEMPLATES_REPO
                      Where init --clone clones from, for an air-gapped client
                      with an internal mirror or an organisation that vendors the
                      templates into its own git server.
  NO_COLOR            Set to anything to disable bold and colour. Colour is also
                      off automatically when the output is not a terminal, so a
                      redirected file or a CI log never contains escape codes.
  LERIAN_SPINNER      ascii falls back from the braille progress spinner to
                      | / - \\, for a terminal or font that renders braille as
                      empty boxes.

EXAMPLES
  lerian-infra init --env dev
  lerian-infra --list
  lerian-infra --env dev --target all --dry-run
  lerian-infra --env dev --target bootstrap --action apply
  lerian-infra --env stg --target infra-base/vpc --action plan
  lerian-infra --env prd --target midaz --action apply --jobs 4
  lerian-infra --env dev --target midaz/postgres --action destroy
  lerian-infra --env dev --target reporter --action helm-values --format yaml \
    > reporter-dev-values.yaml

  A whole environment on shared datastores, from an empty account:
    lerian-infra init --env dev                       # answer: shared
    lerian-infra --env dev --target bootstrap        --action apply
    lerian-infra --env dev --target infra-base       --action apply
    lerian-infra --env dev --target shared-resources --action apply
    lerian-infra --env dev --target midaz --action helm-values --format yaml \
      > midaz-dev-values.yaml
`
