package main

// usage is written by hand rather than generated by the flag package: the flags of
// this command need paragraphs, not one-line descriptions, because most of them
// select which AWS account gets touched.
const usage = `lerian-infra — deploy the AWS v2 stacks of lerian-terraform-foundation

USAGE
  lerian-infra --env <dev|stg|prd> [--target <target>] [--action <action>] [options]

FLAGS
  --repo <path>           The lerian-terraform-foundation checkout to drive.
                          Rarely needed: this command is built from the checkout
                          it drives, so running it anywhere inside one is enough.
                          Resolution order:
                            1. --repo
                            2. $LERIAN_TF_REPO
                            3. walk up from the working directory until a
                               directory holding examples/aws/_modules and
                               examples/aws/backend is found.
                          Use --repo or the variable for a go-installed copy run
                          from outside a checkout.

  --env <dev|stg|prd>     REQUIRED. Selects the AWS account from
                          examples/aws/environments.conf, the backend file
                          examples/aws/backend/<env>.hcl, and the variables file
                          envs/<env>.tfvars inside every stack.

  --target <target>       What to operate on. Default: infra-base.
                            bootstrap                state bucket + lock table
                            infra-base               vpc then eks
                            infra-base/vpc           just the VPC
                            infra-base/eks           just the cluster
                            shared-resources         the whole shared datastore tier
                            shared-resources/<svc>   one shared datastore
                            <product>                every service of one product
                            <product>/<service>      one service
                            all                      everything, in order
                          Products and services are DISCOVERED from
                          examples/aws/products/*/*/main.tf. A new product works
                          the moment its directory exists. Run --list to see them.

  --action <action>       Default: plan.
                            plan          terraform plan only. Changes nothing.
                            apply         plan, show the summary, confirm, apply.
                            destroy       the same, for -destroy plans.
                            helm-values   read helm_values from every service of
                                          the target and merge them into one
                                          document on stdout.
                            output        terraform output for every unit.

  --auto-approve          Skip the single confirmation before apply/destroy.
                          Terraform still applies a saved plan file, so what runs
                          is exactly what was shown.

  --jobs <n>              Services inside one product run in parallel. Default 4.
                          Ordered stages (bootstrap, vpc, eks) are always
                          sequential regardless of this.

  --format <json|yaml>    Output shape for --action helm-values. Default json.

  --dry-run               Resolve and print the execution plan — units, order,
                          state keys, backend file, profile, expected account —
                          then exit. Makes NO AWS call at all.

  --list                  List discoverable targets and exit. Makes no AWS call,
                          reads no configuration.

  --version               Print the version and exit.
  --help                  This text.

THE ACCOUNT GUARD
  Three checks run before anything else, and two of them cost no AWS call:

    1. the state bucket in backend/<env>.hcl ends in -<account_id>, which catches
       a backend file left over from another account;
    2. the region in environments.conf matches the one in backend/<env>.hcl;
    3. aws sts get-caller-identity resolves to the declared account_id.

  There is deliberately no flag to bypass any of them, and --auto-approve does not
  skip them. If the account genuinely changed, edit environments.conf — a
  reviewable, diffable act — instead of typing an override at the end of a long
  day.

ORDER
  apply    bootstrap -> infra-base/vpc -> infra-base/eks
                     -> shared-resources/* -> products/*
  destroy  the exact reverse.

  bootstrap is never destroyed: the bucket and the lock table carry
  prevent_destroy = true. See examples/aws/bootstrap/README.md, "Teardown".

WHY -reconfigure IS ALWAYS PASSED
  .terraform/ caches the resolved backend, including the bucket of whichever
  environment was initialised last. Without -reconfigure, switching environments
  in the same checkout keeps the stale bucket and the run dies with a 403 at apply
  time — long after the plan looked fine. Every init here passes it.

EXAMPLES
  lerian-infra --list
  lerian-infra --env dev --target all --dry-run
  lerian-infra --env dev --target bootstrap --action apply
  lerian-infra --env stg --target infra-base/vpc --action plan
  lerian-infra --env prd --target midaz --action apply --jobs 4
  lerian-infra --env dev --target midaz/postgres --action destroy
  lerian-infra --env dev --target reporter --action helm-values --format yaml \
    > reporter-dev-values.yaml
`
