name: Terraform CI/CD

# Trigger workflow on push to main/develop and PR events
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types:
      - opened      # When PR is created
      - edited      # When PR description/title is edited
      - synchronize # When PR receives new commits
      - reopened    # When PR is reopened

permissions:
  id-token: write       # Needed for authentication
  contents: write       # Needed to create releases and tags
  pull-requests: write  # Needed to create/update PRs

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository code in PR
    - name: Checkout in PR
      uses: actions/checkout@v4
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    # Checkout repository code in push
    - name: Checkout in push
      uses: actions/checkout@v4
      if: github.event_name == 'push'
      with:
        fetch-depth: 0

    # Setup Node.js environment for commitlint
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - run: npm install
    # Run the commitlint action, considering its own dependencies and yours as well 🚀
    # `github.workspace` is the path to your repository.
    # Ensure commits follow conventional commits specification
    - uses: wagoid/commitlint-github-action@v6
      env:
        NODE_PATH: ${{ github.workspace }}/node_modules

    # Install Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Install TFLint for Terraform linting
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4

    - name: Cache plugin dir
      uses: actions/cache@v4
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    # Check Terraform files formatting
    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    # Initialize Terraform working directories
    - name: Terraform Init
      run: |
        # AWS components
        cd examples/aws/vpc && terraform init -backend=false
        cd ../route53 && terraform init -backend=false
        cd ../rds && terraform init -backend=false
        cd ../elasticache && terraform init -backend=false
        cd ../eks && terraform init -backend=false
        # GCP components
        cd ../../../examples/gcp/vpc && terraform init -backend=false
        cd ../cloud-dns && terraform init -backend=false
        cd ../cloud-sql && terraform init -backend=false
        cd ../valkey && terraform init -backend=false
        cd ../gke && terraform init -backend=false
        # Azure components
        cd ../../../examples/azure/network && terraform init -backend=false
        cd ../dns && terraform init -backend=false
        cd ../database && terraform init -backend=false
        cd ../redis && terraform init -backend=false
        cd ../aks && terraform init -backend=false

    # Validate Terraform configurations
    - name: Terraform Validate
      run: |
        # AWS components
        cd examples/aws/vpc && terraform validate
        cd ../route53 && terraform validate
        cd ../rds && terraform validate
        cd ../elasticache && terraform validate
        cd ../eks && terraform validate
        # GCP components
        cd ../../../examples/gcp/vpc && terraform validate
        cd ../cloud-dns && terraform validate
        cd ../cloud-sql && terraform validate
        cd ../valkey && terraform validate
        cd ../gke && terraform validate
        # Azure components
        cd ../../../examples/azure/network && terraform validate
        cd ../dns && terraform validate
        cd ../database && terraform validate
        cd ../redis && terraform validate
        cd ../aks && terraform validate

    # Run TFLint on all Terraform files
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: |
        # Find all .tf files recursively, excluding .terraform directories, and get unique directories
        dirs=$(find . -type f -name "*.tf" -not -path "*/.terraform/*" -exec dirname {} \; | sort -u)

        # Loop through each directory and run tflint using root config
        for dir in $dirs; do
          echo "Linting $dir"
          tflint --chdir="$dir" --config="${{ github.workspace }}/.tflint.hcl"
        done

    # Security scan Terraform code
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        additional_args: "--exclude aws-ssm-secret-use-customer-key,aws-ssm-secret-use-customer-key,aws-ec2-no-public-egress-sgr,aws-ec2-require-vpc-flow-logs-for-all-vpcs,google-sql-encrypt-in-transit-data,google-gke-enable-private-cluster,google-gke-enable-network-policy,google-gke-enforce-pod-security-policy"

    # Preview next semantic-release version
    - name: Preview Next Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        ci: false
        dry_run: true
        semantic_version: 23.0.8
        extra_plugins: |
          conventional-changelog-conventionalcommits@v7.0.2
          @saithodev/semantic-release-backmerge
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GIT_AUTHOR_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
        GIT_AUTHOR_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
        GIT_COMMITTER_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
        GIT_COMMITTER_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}

  release:
    needs: validate  # Only run after validation succeeds
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    # Create GitHub App token for better rate limits
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_APP_ID }}
        private-key: ${{ secrets.LERIAN_STUDIO_MIDAZ_PUSH_BOT_PRIVATE_KEY }}

    # Checkout code with full history for versioning
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history needed for semantic versioning
        token: ${{ steps.app-token.outputs.token }}

    # Setup GPG for signed commits and tags
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      id: import_gpg
      with:
        gpg_private_key: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY }}
        passphrase: ${{ secrets.LERIAN_CI_CD_USER_GPG_KEY_PASSWORD }}
        git_committer_name: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
        git_committer_email: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    # Setup Node.js for semantic-release
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Create new release with semantic versioning
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      with:
        ci: false
        semantic_version: 23.0.8
        extra_plugins: |
          conventional-changelog-conventionalcommits@v7.0.2
          @saithodev/semantic-release-backmerge
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GIT_AUTHOR_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
        GIT_AUTHOR_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}
        GIT_COMMITTER_NAME: ${{ secrets.LERIAN_CI_CD_USER_NAME }}
        GIT_COMMITTER_EMAIL: ${{ secrets.LERIAN_CI_CD_USER_EMAIL }}